# Generated by Django 4.2.3 on 2023-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpattern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vishal',
            name='mobile',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
